Repository Go4Surprise/Go4Surprise, pull requests merged in 2025-04, with the labels that each got.

#82 Fix/cambios
  CHANGELOG.md
  Go4SurpriseFrontend/app/LoginScreen.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  Go4SurpriseFrontend/app/RegisterScreen.tsx
  Go4SurpriseFrontend/package-lock.json
  Go4SurpriseFrontend/package.json
Labels: Review effort 2/5

#83 Enhance/enhance UI
  CHANGELOG.md
  Go4SurpriseFrontend/app/BookingDetails.tsx
  Go4SurpriseFrontend/app/Experiences.tsx
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/app/LoginScreen.tsx
  Go4SurpriseFrontend/app/PreferencesFormScreen.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  Go4SurpriseFrontend/app/RegisterBookings.tsx
  Go4SurpriseFrontend/app/RegisterScreen.tsx
  Go4SurpriseFrontend/app/Reviews.tsx
  Go4SurpriseFrontend/package-lock.json
  Go4SurpriseFrontend/package.json
Labels: Review effort 4/5

#84 Enhance UI: mejora visual global en varias partes
  CHANGELOG.md
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/app/MyBookings.tsx
  Go4SurpriseFrontend/app/RegisterBookings.tsx
Labels: Review effort 2/5

#87 fix: enhance UI
  CHANGELOG.md
  Go4SurpriseFrontend/app/(tabs)/index.tsx
  Go4SurpriseFrontend/app/+not-found.tsx
  Go4SurpriseFrontend/app/AdminBookingsDetail.tsx
  Go4SurpriseFrontend/app/AdminBookingsPanel.tsx
  Go4SurpriseFrontend/app/AdminPanel.tsx
  Go4SurpriseFrontend/app/AdminUserPanel.tsx
  Go4SurpriseFrontend/app/CountDown.tsx
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/app/IntroPreferencesScreen.tsx
  Go4SurpriseFrontend/app/LoginScreen.tsx
  Go4SurpriseFrontend/app/MyBookings.tsx
  Go4SurpriseFrontend/app/PreferencesFormScreen.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  Go4SurpriseFrontend/components/AdminDashboard.tsx
  Go4SurpriseFrontend/components/AdminHeader.tsx
Labels: Review effort 3/5

#88 Feature/add to calendar
  CHANGELOG.md
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/app/MyBookings.tsx
  Go4SurpriseFrontend/package-lock.json
  Go4SurpriseFrontend/package.json
  Go4SurpriseFrontend/types/bookingTypes.ts
  backend/bookings/migrations/0004_booking_payment_intent_id_alter_booking_status.py
  backend/bookings/models.py
  backend/bookings/serializers.py
  backend/bookings/views.py
Labels: Review effort 4/5

#89 Feature/add to calendar
  CHANGELOG.md
  Go4SurpriseFrontend/app/CountDown.tsx
  Go4SurpriseFrontend/app/MyBookings.tsx
  backend/bookings/views.py
Labels: Review effort 2/5

#90 Feature/pistas experiencia
  CHANGELOG.md
  Go4SurpriseFrontend/app.yaml
  Go4SurpriseFrontend/app/AdminBookingsDetail.tsx
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/constants/apiUrl.ts
  Go4SurpriseFrontend/package-lock.json
  backend/app.yaml
  backend/bookings/management/commands/notify_experience_details.py
  backend/bookings/management/commands/notify_hints.py
  backend/bookings/urls.py
  backend/bookings/views.py
  backend/go4surprise/settings.py
  backend/reviews/views.py
  backend/users/migrations/0007_usuario_birthdate.py
  backend/users/views.py
Labels: Review effort 4/5

#91 fix: some codacy issues has been fixed
  CHANGELOG.md
  Go4SurpriseFrontend/app/(tabs)/index.tsx
  Go4SurpriseFrontend/app/AdminBookingsDetail.tsx
  Go4SurpriseFrontend/app/AdminBookingsPanel.tsx
  Go4SurpriseFrontend/app/BookingDetails.tsx
  Go4SurpriseFrontend/app/Experiences.tsx
  Go4SurpriseFrontend/app/LoginScreen.tsx
  Go4SurpriseFrontend/app/MyBookings.tsx
  Go4SurpriseFrontend/app/PasswordResetConfirm.tsx
  Go4SurpriseFrontend/app/PreferencesFormScreen.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  Go4SurpriseFrontend/app/RegisterScreen.tsx
  Go4SurpriseFrontend/app/Reviews.tsx
Labels: Review effort 2/5

#95 Experiences descriptions
  CHANGELOG.md
  Go4SurpriseFrontend/app/AdminBookingsDetail.tsx
  Go4SurpriseFrontend/app/AdminBookingsPanel.tsx
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/app/MyBookings.tsx
  Go4SurpriseFrontend/components/AdminHeader.tsx
  Go4SurpriseFrontend/package-lock.json
  Go4SurpriseFrontend/package.json
  backend/bookings/serializers.py
  backend/bookings/views.py
  backend/users/urls.py
  backend/users/views.py
Labels: Review effort 3/5

#97 fix: Arreglar errores
  CHANGELOG.md
  Go4SurpriseFrontend/app/AdminBookingsDetail.tsx
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/app/PreferencesFormScreen.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  Go4SurpriseFrontend/app/_layout.tsx
  backend/users/views.py
Labels: Review effort 3/5

#99 Fix booking details mobile
  CHANGELOG.md
  Go4SurpriseFrontend/app/AdminBookingsDetail.tsx
  Go4SurpriseFrontend/app/AdminBookingsPanel.tsx
  Go4SurpriseFrontend/app/PasswordResetConfirm.tsx
  Go4SurpriseFrontend/app/Profile.tsx
Labels: Review effort 2/5

#94 Feature/pro emails
  CHANGELOG.md
  Go4SurpriseFrontend/app/RegisterScreen.tsx
  backend/bookings/templates/emails/base_email.html
  backend/bookings/templates/emails/cancelacion.html
  backend/bookings/templates/emails/confirmacion.html
  backend/bookings/views.py
  backend/users/templates/emails/base_email.html
  backend/users/templates/emails/email_verificacion.html
  backend/users/templates/emails/password_reset.html
  backend/users/views.py
Labels: Review effort 3/5

#98 Pruebas
  .gitignore
  CHANGELOG.md
  Go4SurpriseFrontend/package-lock.json
  Go4SurpriseFrontend/package.json
  backend/.coverage
  backend/.coveragerc
  backend/bookings/serializers.py
  backend/bookings/tests.py
  backend/dev/profile_pics/84e9ca7c-5473-42cf-a2f6-d912e620da0a_2bfdaf8aa181437bb96fab6dcbb1b91c.jpg
  backend/experiences/tests.py
  backend/experiences/views.py
  backend/pytest.ini
  backend/requirements.txt
  backend/reviews/tests.py
  backend/tests/__init__.py
  backend/tests/pruebas_aceptacion/__pycache__/test_inicio.cpython-310-pytest-8.3.5.pyc
  backend/tests/pruebas_aceptacion/__pycache__/test_perfil.cpython-310-pytest-8.3.5.pyc
  backend/tests/pruebas_aceptacion/__pycache__/test_registro.cpython-310-pytest-8.3.5.pyc
  backend/tests/pruebas_aceptacion/añadir_calendario.py
  backend/tests/pruebas_aceptacion/cancelar_reserva.py
  backend/tests/pruebas_aceptacion/crear_reserva.py
  backend/tests/pruebas_aceptacion/listar_reservas.py
  backend/tests/pruebas_aceptacion/pagar_reserva.py
  backend/tests/pruebas_aceptacion/test_inicio.py
  backend/tests/pruebas_aceptacion/test_perfil.py
  backend/tests/pruebas_aceptacion/test_registro.py
  backend/tests/pruebas_aceptacion/test_reseña.py
  backend/tests/pruebas_rendimiento/__pycache__/locustfile_bookings.cpython-312.pyc
  backend/tests/pruebas_rendimiento/__pycache__/locustfile_experiences.cpython-312.pyc
  backend/tests/pruebas_rendimiento/__pycache__/locustfile_reviews.cpython-312.pyc
  backend/tests/pruebas_rendimiento/__pycache__/locustfile_users.cpython-312.pyc
  backend/tests/pruebas_rendimiento/locustfile_bookings.py
  backend/tests/pruebas_rendimiento/locustfile_experiences.py
  backend/tests/pruebas_rendimiento/locustfile_reviews.py
  backend/tests/pruebas_rendimiento/locustfile_users.py
  backend/tests/test_integration.py
  backend/tests/test_integration_reviews.py
  backend/tests/test_unity_bookings.py
  backend/tests/test_unity_experiences.py
  backend/tests/test_unity_reviews.py
  backend/tests/test_unity_users.py
  backend/users/tests.py
Labels: Review effort 3/5

#101 Fix/errores
  CHANGELOG.md
  Go4SurpriseFrontend/app/AdminBookingsDetail.tsx
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/app/RegisterScreen.tsx
  Go4SurpriseFrontend/app/UserDetails/[id].tsx
  backend/bookings/serializers.py
  backend/bookings/templates/emails/confirmacion.html
  backend/bookings/templates/emails/experiencia.html
  backend/bookings/templates/emails/pista.html
  backend/bookings/views.py
  backend/tests/pruebas_aceptacion/__pycache__/test_reseña.cpython-310-pytest-8.3.5.pyc
  backend/users/admin.py
  backend/users/views.py
Labels: Review effort 2/5

#103 feat: improve landing page
  CHANGELOG.md
  Go4SurpriseFrontend/app/(tabs)/index.tsx
Labels: Review effort 3/5
