Repository Go4Surprise/Go4Surprise, pull requests merged in 2025-05, with the labels that each got.

#104 fix: Arreglo login google
  CHANGELOG.md
  Go4SurpriseFrontend/app.json
  Go4SurpriseFrontend/app.yaml
  Go4SurpriseFrontend/app/LoginScreen.tsx
  Go4SurpriseFrontend/app/_layout.tsx
  Go4SurpriseFrontend/constants/apiUrl.ts
Labels: Review effort 2/5

#107 Feature press enter
  CHANGELOG.md
  Go4SurpriseFrontend/app/LoginScreen.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  Go4SurpriseFrontend/app/RegisterBookings.tsx
  Go4SurpriseFrontend/app/RegisterScreen.tsx
  Go4SurpriseFrontend/package-lock.json
  package-lock.json
Labels: enhancement, Review effort 2/5

#108 fix: eliminar cuenta, mis reservas en home y mensaje éxito registro
  CHANGELOG.md
  Go4SurpriseFrontend/app/(tabs)/index.tsx
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  Go4SurpriseFrontend/app/RegisterScreen.tsx
Labels: Review effort 2/5

#110 Fix: Stripe webhook resolved
  CHANGELOG.md
  Go4SurpriseFrontend/app/MyBookings.tsx
  backend/go4surprise/settings.py
Labels: Review effort 1/5

#111 Arreglos finales
  CHANGELOG.md
  Go4SurpriseFrontend/app/BookingDetails.tsx
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/app/LoginScreen.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  backend/users/views.py
Labels: Review effort 2/5
