Repository Go4Surprise/Go4Surprise, pull requests merged in 2025-03, with the labels that each got.

#36 Implementación de los mensajes de error en el registro
  Go4SurpriseFrontend/app/RegisterScreen.tsx
  backend/users/urls.py
  backend/users/views.py
Labels: bug

#67 Feature/politica privacidad
  CHANGELOG.md
  Go4SurpriseFrontend/app/(tabs)/index.tsx
  Go4SurpriseFrontend/app/CondicionesUso.tsx
  Go4SurpriseFrontend/app/PoliticaPrivacidad.tsx
  Go4SurpriseFrontend/app/RegisterScreen.tsx
  Go4SurpriseFrontend/app/_layout.tsx
Labels: Review effort 2/5

#66 Feature/Hints Experiences + Admin Panel Bookings
  CHANGELOG.md
  Go4SurpriseFrontend/app/AdminBookingsDetail.tsx
  Go4SurpriseFrontend/app/AdminBookingsPanel.tsx
  Go4SurpriseFrontend/app/HomeScreen.tsx
  Go4SurpriseFrontend/app/MyBookings.tsx
  Go4SurpriseFrontend/components/AdminDashboard.tsx
  Go4SurpriseFrontend/package-lock.json
  backend/bookings/admin.py
  backend/bookings/models.py
  backend/bookings/serializers.py
  backend/bookings/tests.py
  backend/bookings/urls.py
  backend/bookings/views.py
  backend/experiences/forms.py
  backend/experiences/urls.py
  backend/experiences/views.py
  backend/requirements.txt
Labels: Review effort 4/5

#69 Feature/booking payment
  CHANGELOG.md
  Go4SurpriseFrontend/app/BookingDetails.tsx
  Go4SurpriseFrontend/app/RegisterBookings.tsx
  Go4SurpriseFrontend/app/_layout.tsx
  Go4SurpriseFrontend/constants/apiUrl.ts
  Go4SurpriseFrontend/package-lock.json
  Go4SurpriseFrontend/package.json
  backend/bookings/urls.py
  backend/bookings/views.py
  backend/go4surprise/settings.py
  backend/requirements.txt
Labels: Review effort 4/5

#70 fix: Arreglo de errores
  CHANGELOG.md
  Go4SurpriseFrontend/app/ForgottenPasword.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  Go4SurpriseFrontend/app/_layout.tsx
Labels: bug, Review effort 1/5

#71 Fixes en panel admin
  CHANGELOG.md
  Go4SurpriseFrontend/app/AdminBookingsDetail.tsx
Labels: Review effort 2/5

#74 Revert "Merge pull request #64 from Go4Surprise/feature/arreglar-perfil"
  CHANGELOG.md
  Go4SurpriseFrontend/app/MyBookings.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  Go4SurpriseFrontend/package-lock.json
  Go4SurpriseFrontend/package.json
  backend/bookings/urls.py
  backend/bookings/views.py
  backend/users/serializers.py
  backend/users/views.py
Labels: Review effort 2/5

#73 fix: stripe in same page
  CHANGELOG.md
  Go4SurpriseFrontend/app/BookingDetails.tsx
  Go4SurpriseFrontend/app/LoginScreen.tsx
  backend/bookings/views.py
Labels: Review effort 1/5

#72 Fix/cancel booking
  CHANGELOG.md
  Go4SurpriseFrontend/app/MyBookings.tsx
  backend/bookings/urls.py
  backend/bookings/views.py
  backend/go4surprise/settings.py
Labels: Review effort 2/5

#76 fix: countdown fixed
  CHANGELOG.md
  Go4SurpriseFrontend/app/CountDown.tsx
Labels: Review effort 2/5

#81 fix: Add user profile code and fix design issues
  CHANGELOG.md
  Go4SurpriseFrontend/app/(tabs)/index.tsx
  Go4SurpriseFrontend/app/CondicionesUso.tsx
  Go4SurpriseFrontend/app/LoginScreen.tsx
  Go4SurpriseFrontend/app/PoliticaPrivacidad.tsx
  Go4SurpriseFrontend/app/Profile.tsx
  Go4SurpriseFrontend/app/RegisterScreen.tsx
  Go4SurpriseFrontend/package-lock.json
  Go4SurpriseFrontend/package.json
Labels: Review effort 3/5
